name: Python CI pipeline

on:
  push:
  pull_request:

jobs:


  Python-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        #this action is a reusuable task which can be used inside the workflow,it makes our repo available inside the runner ubuntu

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          


      - name: Run automated test

        run: pytest

  terraform-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.0"

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

  deploy:
    needs:
      - Python-test
      - terraform-validation

    runs-on: ubuntu-latest

    steps:
      - name: Simulate deployment
        run: echo "everything passed mf"
